---
# Shared variables for app_servers group

# Node.js settings
nodejs_setup_url: "https://deb.nodesource.com/setup_20.x"
nodejs_package: "nodejs"

# PM2
pm2_package: "pm2"

# PostgreSQL settings
pg_packages:
  - postgresql
  - postgresql-contrib
  - python3-psycopg2
db_host: "{{ db_host }}"
db_port: "{{ db_port }}"
db_name: "{{ db_name }}"
db_user: "{{ db_user }}"
db_password: "{{ db_password }}"

# Application settings
app_repo: "https://github.com/mraifalkautsar/node-app"
app_repo_version: main
app_deploy_dir: /srv/node-app
app_user: "{{ ansible_user }}"
app_port: 3000
node_env: production
